### ISSUE TITLE
Tool is running curl which exposing auth header to the processlist

### ISSUE THREAD

**Issue by samm-git** [hashicorp/tfe-cli#33]
Hi, 

I found that tool itself is running curl, at least on some operations. This exposing TFE token as curl cli, what could be an issue on multi-user env. I think this should be fixed.

**Comment by fprimex** [comment]
Thanks for raising this concern. The way to fix this and continue to use `curl` would be, I believe, to use a curl config file:

https://ec.haxx.se/cmdline-passwords.html

https://github.com/curl/curl/issues/679

I could add an option to refer to a curl config file containing the header, and/or check some "standard" location such as `~/.tfe-cli-curl` or something else. Would that resolve this? The process list would show `curl -K ...` instead of the token in the `--header` option.

**Comment by samm-git** [comment]
Hi, yes, could be an option. Best way is probably to not use curl directly at all and to use libcurl (or whatever) programmatically

**Comment by fprimex** [comment]
I agree with the approach of using a library where possible. This particular project / codebase is written in portable shell, and the `curl` command is by far the most accessible and common command for accomplishing the task of making the actual API requests (also, the documentation examples use `curl`).

I will see if I can get the config file approach going. A different codebase in another language such as Go, whether it succeeds this project or coexists with it, will take a different approach where I'm sure this won't be an issue.

**Comment by fprimex** [comment]
Submitted https://github.com/hashicorp/tfe-cli/pull/43

This will create and manage a `.tfe-cli-curl` file, which can come from `.terraformrc`, `$ATLAS_TOKEN`, `$TFE_TOKEN`, or `-token`, and can be written with `tfe config [...] -write`. The PR has examples that explain this better and will go into the readme with the pending docs overhaul.

**Comment by fprimex** [comment]
`tfe-cli` is getting deprecated, but no worries because I have already done a full rewrite of a lot of it which is published here under the community repos:

https://github.com/hashicorp-community/tf-helper

That version has a `curl-config` command to aid in getting the curl configuration file set up! If it breaks please file an issue over there :)
